import React from 'react';
import { cn } from "@/lib/utils";
import AdminLayout from '../../components/AdminLayout';
import { FileText, Download, Users, Wallet, Sprout, Beef, MoreVertical, ArrowRight, Clock } from 'lucide-react';
import { Card } from '@/shared/components/ui/card';
import { Button } from '@/shared/components/ui/button';
import { Checkbox } from '@/shared/components/ui/checkbox';
import adminService from '../../services/admin.api';
import { useAdminData } from '../../hooks/useAdminData';
import DataTable from '../../components/DataTable';
import { formatDate } from '../../utils/helpers';
import { toast } from 'sonner';
const Reports = () => {
    const { data: reportsData, loading, refresh } = useAdminData({
        fetchFn: () => adminService.listReports()
    });
    const reportTemplates = [
        { id: 'farmers', title: 'Farmer Demographic Registry', description: 'Complete list of registered farmers with contact and farm specifications.', icon: Users, color: 'text-blue-500 bg-blue-50' },
        { id: 'finance', title: 'Ecosystem Financial Summary', description: 'System-wide income and expense records with categorical breakdown.', icon: Wallet, color: 'text-emerald-500 bg-emerald-50' },
        { id: 'crops', title: 'Platform Cultivation Metrics', description: 'Monitoring of current growth stages and expected yield across all fields.', icon: Sprout, color: 'text-amber-500 bg-amber-50' },
        { id: 'livestock', title: 'Livestock Health & Stats', description: 'Animal inventory monitoring, health states, and breeding cycles.', icon: Beef, color: 'text-purple-500 bg-purple-50' },
    ];
    const handleGenerate = async (id) => {
        try {
            toast.loading(`Generating ${id} report...`);
            // In a real app, this would call an API to trigger generation
            setTimeout(() => {
                toast.dismiss();
                toast.success(`${id.charAt(0).toUpperCase() + id.slice(1)} report generated successfully!`);
                refresh();
            }, 1500);
        }
        catch (error) {
            toast.error('Failed to generate report');
        }
    };
    const columns = [
        {
            header: 'Report Name',
            accessor: (r) => (<div className="flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center text-slate-400 group-hover:bg-blue-600 group-hover:text-white transition-all shadow-sm">
             <FileText className="w-5 h-5"/>
          </div>
          <div>
             <p className="font-bold text-slate-700 tracking-tight">{r.name}</p>
             <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mt-0.5">{r.report_type}</p>
          </div>
        </div>),
        },
        {
            header: 'Created On',
            accessor: (r) => (<span className="text-sm font-bold text-slate-500">{formatDate(r.created_at || new Date().toISOString())}</span>),
        },
        {
            header: 'Size',
            accessor: (r) => (<span className="text-xs font-bold text-slate-400">{r.file_size || '2.4 MB'}</span>),
        },
        {
            header: 'Generated By',
            accessor: (r) => (<span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">{r.created_by_name}</span>),
        },
        {
            header: 'Actions',
            className: 'text-right',
            headerClassName: 'text-right',
            accessor: (r) => (<div className="flex items-center justify-end gap-2">
           <Button variant="ghost" size="icon" className="rounded-full h-9 w-9 transition-all hover:bg-emerald-50 hover:text-emerald-600">
              <Download className="w-4 h-4"/>
           </Button>
           <Button variant="ghost" size="icon" className="rounded-full h-9 w-9">
              <MoreVertical className="w-4 h-4 text-slate-300"/>
           </Button>
        </div>),
        },
    ];
    return (<AdminLayout>
      <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <div>
          <h1 className="text-3xl font-extrabold text-slate-800 tracking-tight">Intelligence & Reporting</h1>
          <p className="text-slate-500 font-medium">Generate deep-insight documents and raw data exports.</p>
        </div>

        <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
           {/* Custom Builder */}
           <Card className="xl:col-span-1 p-8 border-slate-100 flex flex-col">
              <h3 className="text-xl font-black text-slate-800 mb-6">Custom Report Builder</h3>
              
              <div className="space-y-6 flex-1">
                 <div className="space-y-3">
                    <label className="text-xs font-black text-slate-400 uppercase tracking-widest pl-1">Target Dimension</label>
                    <div className="grid grid-cols-1 gap-2">
                       {['Farmer Stats', 'Crop Records', 'Livestock Logs', 'Financial Ledger'].map((item) => (<div key={item} className="flex items-center space-x-3 p-3 rounded-xl border border-slate-100 hover:bg-slate-50 transition-colors cursor-pointer">
                            <Checkbox id={item} className="rounded-md"/>
                            <label htmlFor={item} className="text-sm font-bold text-slate-600 cursor-pointer flex-1">{item}</label>
                         </div>))}
                    </div>
                 </div>

                 <div className="space-y-3">
                    <label className="text-xs font-black text-slate-400 uppercase tracking-widest pl-1">Time Dimension</label>
                    <div className="grid grid-cols-2 gap-3">
                       <div className="p-3 rounded-xl border border-slate-100 space-y-1">
                          <p className="text-[10px] font-black text-slate-300 uppercase">Start Date</p>
                          <p className="text-xs font-bold text-slate-600">2026-01-01</p>
                       </div>
                       <div className="p-3 rounded-xl border border-slate-100 space-y-1">
                          <p className="text-[10px] font-black text-slate-300 uppercase">End Date</p>
                          <p className="text-xs font-bold text-slate-600">Present</p>
                       </div>
                    </div>
                 </div>
              </div>

              <Button className="w-full mt-10 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white py-6 font-black shadow-lg shadow-emerald-100 gap-2">
                 Generate Custom Report <ArrowRight className="w-4 h-4"/>
              </Button>
           </Card>

           {/* Templates & History */}
           <div className="xl:col-span-2 space-y-8">
              {/* Templates */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                 {reportTemplates.map((tpl) => (<Card key={tpl.id} className="p-6 border-slate-100 group transition-all duration-300 hover:shadow-xl hover:border-emerald-100">
                      <div className="flex justify-between items-start mb-4">
                         <div className={cn("p-4 rounded-2xl transition-colors", tpl.color)}>
                            <tpl.icon className="w-6 h-6"/>
                         </div>
                         <Button variant="ghost" className="text-emerald-600 font-bold gap-2 rounded-xl group-hover:bg-emerald-50 transition-all px-4" onClick={() => handleGenerate(tpl.id)}>
                            Build <Download className="w-4 h-4"/>
                         </Button>
                      </div>
                      <h4 className="text-lg font-black text-slate-800 mb-2">{tpl.title}</h4>
                      <p className="text-sm font-medium text-slate-400 leading-relaxed">{tpl.description}</p>
                   </Card>))}
              </div>

              {/* Generated History */}
              <Card className="border-slate-100 shadow-sm overflow-hidden">
                 <div className="p-6 border-b border-slate-50 flex items-center justify-between">
                    <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                       <Clock className="w-5 h-5 text-slate-300"/>
                       Report Archive
                    </h3>
                 </div>
                 
                 <DataTable columns={columns} data={reportsData?.reports || []} loading={loading} emptyMessage="No reports have been generated yet."/>
              </Card>
           </div>
        </div>
      </div>
    </AdminLayout>);
};
export default Reports;
