// src/features/admin/reports/components/ReportHistoryTable.jsx
import React from 'react';
import { FileText, MoreVertical, Download, Trash2, Calendar, Clock } from 'lucide-react';
import { Button } from '@/shared/components/ui/button';
import { Checkbox } from '@/shared/components/ui/checkbox';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from '@/shared/components/ui/dropdown-menu';
import { formatDate } from '../../utils/helpers';

const ReportHistoryTable = ({ 
  reports, 
  loading, 
  selectedReports, 
  onToggleSelect,
  onSelectAll,
  onDownload,
  onDelete
}) => {
  // Debug log
  console.log('📊 ReportHistoryTable received reports:', reports);
  console.log('📊 ReportHistoryTable reports length:', reports?.length);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-600"></div>
      </div>
    );
  }

  if (!reports || reports.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-slate-400">
        <FileText className="w-12 h-12 mb-3" />
        <p className="text-sm font-medium">No reports generated yet</p>
        <p className="text-xs">Generate your first report using the templates above</p>
      </div>
    );
  }

  const columns = [
    {
      header: '',
      accessor: (r) => (
        <Checkbox
          checked={selectedReports.includes(r.id)}
          onCheckedChange={() => onToggleSelect(r.id)}
        />
      ),
    },
    {
      header: 'Report Name',
      accessor: (r) => (
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center">
            <FileText className="w-4 h-4 text-slate-500"/>
          </div>
          <div>
            <p className="font-bold text-slate-700 text-sm">{r.title || r.report_type}</p>
            <p className="text-[10px] text-slate-400 capitalize">{r.report_type}</p>
          </div>
        </div>
      ),
    },
    {
      header: 'Date Range',
      accessor: (r) => (
        <div className="flex flex-col gap-0.5">
          <div className="flex items-center gap-1 text-xs text-slate-600">
            <Calendar className="w-3 h-3 text-slate-400" />
            <span>From: {r.filters?.start_date || 'N/A'}</span>
          </div>
          <div className="flex items-center gap-1 text-xs text-slate-600">
            <Calendar className="w-3 h-3 text-slate-400" />
            <span>To: {r.filters?.end_date || 'N/A'}</span>
          </div>
        </div>
      ),
    },
    {
      header: 'Created',
      accessor: (r) => (
        <div className="flex flex-col gap-0.5">
          <span className="text-xs text-slate-700">{formatDate(r.generated_at)}</span>
          <span className="text-[10px] text-slate-400">
            <Clock className="w-3 h-3 inline mr-1" />
            {r.generated_at ? new Date(r.generated_at).toLocaleTimeString() : 'N/A'}
          </span>
        </div>
      ),
    },
    {
      header: 'Format',
      accessor: (r) => (
        <span className="text-xs font-bold text-slate-400 uppercase px-2 py-1 bg-slate-100 rounded">
          {r.format}
        </span>
      ),
    },
    {
      header: 'Generated By',
      accessor: (r) => (
        <span className="text-xs text-slate-500">{r.generated_by_name || 'System'}</span>
      ),
    },
    {
      header: '',
      className: 'text-right',
      accessor: (r) => (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon" className="h-8 w-8">
              <MoreVertical className="w-4 h-4 text-slate-400"/>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-40">
            <DropdownMenuItem onClick={() => onDownload(r)} className="gap-2">
              <Download className="w-4 h-4"/> Download
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem 
              onClick={() => onDelete(r)} 
              className="gap-2 text-red-600"
            >
              <Trash2 className="w-4 h-4"/> Delete
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      ),
    },
  ];

  return (
    <div className="overflow-x-auto">
      <table className="w-full">
        <thead className="bg-slate-50 border-b border-slate-200">
          <tr>
            <th className="px-4 py-3 text-left">
              <Checkbox
                checked={selectedReports.length === reports.length && reports.length > 0}
                onCheckedChange={onSelectAll}
              />
            </th>
            {columns.slice(1).map((col, index) => (
              <th key={index} className="px-4 py-3 text-left text-xs font-bold text-slate-500 uppercase tracking-wider">
                {col.header}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-100">
          {reports.map((report) => (
            <tr key={report.id} className="hover:bg-slate-50 transition-colors">
              {columns.map((col, index) => (
                <td key={index} className={`px-4 py-3 ${col.className || ''}`}>
                  {col.accessor(report)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default ReportHistoryTable;